"""add book description

Revision ID: 31abd46c1fcb
Revises: 75a135f0e1f6
Create Date: 2025-11-02 23:12:15.546634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31abd46c1fcb'
down_revision = '75a135f0e1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
