"""init schema

Revision ID: 75a135f0e1f6
Revises: 
Create Date: 2025-11-02 22:53:39.990027

"""
from alembic import op
import sqlalchemy as sa

from run import app
from app.models.types import EpochMsDate

# revision identifiers, used by Alembic.
revision = '75a135f0e1f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=sa.DATE(),
               type_=EpochMsDate(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('order_date',
               existing_type=EpochMsDate(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
