"""author birth date added

Revision ID: 97fc473cbcdc
Revises: 31abd46c1fcb
Create Date: 2025-11-03 09:10:16.511322

"""
from alembic import op
import sqlalchemy as sa

from app.models.types import EpochMsDate

# revision identifiers, used by Alembic.
revision = '97fc473cbcdc'
down_revision = '31abd46c1fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', EpochMsDate(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
